spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oos
    username: root
    password: Samsun55.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

