spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oos
    username: root
    password: Samsun55.
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  ###### Email Properties ######
  #smtp mail properties
  mail:
    host: smtp.gmail.com
    port: 587
    username: yussufatalarr@gmail.com
    password: ytqniyqcmnubzjsu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


server:
  port: 8080
SECRET_KEY: 556A586E3272357538782F413F4428472B4B6250655368566B59703373367639
RANDOM_RATE: 0.2